# .pre-commit-config.yaml

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # Latest stable version for pre-commit-hooks
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 7.2.0  # Ensure this is the correct version for flake8
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8==7.2.0
      args:
        - '--max-line-length=200'

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1  # Latest stable version for isort
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 25.1.0  # Corrected version to a stable one
  hooks:
    - id: black
      language_version: python3
